### ISSUE TITLE
extra prey lines

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/interaction-data#5] opened 2015-07-03 16:03 UTC
Prior to June 9, there were a little over 78,500 lines (total interactions). On June 9, I uploaded one reference (4o) that was only 538 lines. That should have brought the count up to about 79,000 lines. Now the counter shows 80,380 total interactions. Where did the extra lines come from? @jhpoelen @jsimons9

**Comment by jsimons9** [comment] 2015-07-03 16:06
Thanks Theresa!!

Jim

**Comment by jhpoelen** [comment] 2015-07-29 17:45
Thanks for reporting this concern @tmitchell1 .

According to the commit log of gomexsi/interaction-data commits after April 2015 where:

| commit | date | # lines in Prey.csv |
| --- | --- | --- |
| e51f18e016f26627d4c264797869c910f1baefdd | 9 June 2015 | 24,510 |
| c00b359b220be168e0396f1b357949f428226474 | 2 June 2015 | 23,972 |
| f7a043836d084edc172b1de9bb83aeb4cb927857 | 22 May 2015 | 13,926 |
| 299bb8cd10c7d5d73795cdbd63433646fe9578d3 | 13 April 2015 | 12,887 |

GloBI released new datasets on 17 April 2015, 20 April 2015, 25 April 2015,  6 May 2015, 21 May 2015, 25 May 2015, 29 May 2015, 6 June 2015 (78,725 gomexsi interactions, includes 2 June 2015 commit), 11 June 2015, 13 June 2015 (w/ taxon integration outages), 18 June 2015, 23 June 2015, 28 June 2015, 2 July 2015, etc. . At time of writing, 80,380 gomexsi interactions are reported. 

As you can see the GloBI release process takes about 3-4 days at this point. Also note the break 6-21 May 2015: this was caused by an unplanned outage of EOL APIs. 

I suspect that fixes in interaction data make more interaction data available through fixed links between references and interaction data. I'll take some time to review the GoMexSI data commits.

**Comment by jhpoelen** [comment] 2015-07-29 18:40
@tmitchell1 I was able to reproduce the observed differences between 2 June and 9 June GoMexSI changes.

I wrote a special program (a test script see above) to ingest and count interactions of GoMexSI v 2 June 2015 c00b359b220be168e0396f1b357949f428226474 and 9 June 2015 e51f18e016f26627d4c264797869c910f1baefdd . The observed difference in interactions was   (55150 - 53495 = 1655), same as the difference between the GoMexSI statistics readings (80380 - 78725 = 1655).

Please note that the first example includes only the GoMexSI data from https://github.com/gomexsi/interaction-data . The second count includes **all** GoMexSI data, including Akin et al. 2006, Blewett et al. 2006 and other raw datasets.

So, as far as GloBI is concerned, the difference in interaction count can be explained by the changes made in GoMexSI data in commit of 9 June 2015 e51f18e016f26627d4c264797869c910f1baefdd . This suggests that the assumption that only 538 lines (or interactions) were added in 9 June 2015 needs to be revisited. 

@tmitchell1 I'd suggest to use available GloBI access tools and github tools to better understand what changes were applied. This is a great example of where we can use our (powerful!) tools like GitHub and GloBI to analyze and understand interaction data. If you find any unexpected results, please open a new issue.

Suggest to close this issue as the reported difference in interaction count is expected.

Hope this helps!

**Comment by jhpoelen** [comment] 2016-02-10 16:14
@tmitchell1 please close this issue it has been resolved.

**Closed as completed** 2016-02-10 16:21 UTC
